packages:
  - apps/*
  - packages/*
allowBuilds:
  "cpu-features@0.0.10": false
  esbuild: true
  "protobufjs@7.6.5": false
  "ssh2@1.17.0": false
minimumReleaseAgeExclude:
  - "@types/react-dom@19.2.5"
